/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HostSlugRouteImport } from './routes/host.$slug'

const HostSlugRoute = HostSlugRouteImport.update({
  id: '/host/$slug',
  path: '/host/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/host/$slug': typeof HostSlugRoute
}
export interface FileRoutesByTo {
  '/host/$slug': typeof HostSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/host/$slug': typeof HostSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/host/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/host/$slug'
  id: '__root__' | '/host/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HostSlugRoute: typeof HostSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/host/$slug': {
      id: '/host/$slug'
      path: '/host/$slug'
      fullPath: '/host/$slug'
      preLoaderRoute: typeof HostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HostSlugRoute: HostSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
